steps:
  - id: unshallowRepository
    name: gcr.io/cloud-builders/git
    waitFor: ['-']
    args: ['fetch', '--unshallow']

  - id: detectSecrets
    name: gcr.io/${PROJECT_ID}/detect-secrets-docker-ci:latest
    waitFor: ['unshallowRepository']
